name: test

on:
  push:
    branches:
      - master
      - 'release/**'
  pull_request:

jobs:
  integration:
    name: Integration tests
    strategy:
      matrix:
        platform: [macos-11]
    runs-on: ${{ matrix.platform }}
    timeout-minutes: 40
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Show host info
        run: |
          uname -a
          sw_vers
          ifconfig
      - name: Install build dependencies of VDE
        run: brew install autoconf automake
      - name: Make Install (x86_64)
        run: |
          # compile for x86_64
          sudo make PREFIX=/opt/vde install
          file /opt/vde/bin/* | grep -c x86_64
      - name: Cleanup
        run: |
          sudo make clean
      - name: Make Install (arm64)
        run: |
          # cross-compile for arm64
          sudo make PREFIX=/opt/vde.arm64 ARCH=arm64 install
          file /opt/vde.arm64/bin/* | grep -c arm64
      - name: Print launchd status (shared mode)
        run: launchctl print system/io.github.lima-vm.vde_vmnet.plist
      - name: Install test dependencies
        run: brew install qemu bash coreutils
      - name: Test (shared mode)
        run: ./test/test.sh /var/run/vde.ctl
# Bridged mode cannot be tested on GHA
